---
# tasks file for wdijkerman.zabbix

- name: "Fix facts for linuxmint - distribution release"
  set_fact:
    ansible_distribution_release: xenial
  when:
    - ansible_os_family == "Linuxmint"
    - ansible_distribution_release == "sonya" or ansible_distribution_release == "serena"

- name: "Fix facts for linuxmint - family"
  set_fact:
    ansible_os_family: Debian
  when: ansible_os_family == "Linuxmint"

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - zabbix-agent

- name: "Install the correct repository"
  include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Fail invalid specified agent_listeninterface"
  fail:
    msg: "The specified network interface does not exist"
  when:
    - zabbix_agent_listeninterface
    - (zabbix_agent_listeninterface not in ansible_all_ipv4_addresses)
  tags:
    - zabbix-agent
    - config

- name: "Fail invalid specified agent_listenip"
  fail:
    msg: "The agent_listenip does not exist"
  when:
    - zabbix_agent_listenip != '0.0.0.0'
    - zabbix_agent_listenip != '127.0.0.1'
    - (zabbix_agent_listenip not in ansible_all_ipv4_addresses)
  tags:
    - zabbix-agent
    - config

- name: "Install the correct repository"
  include_tasks: Linux.yml
  when: ansible_os_family != "Windows"

- name: "Congire zabbix server via API"
  include_tasks: api.yml
  when:
    - zabbix_api_create_hostgroup | bool
    - zabbix_api_create_hosts | bool
    - zabbix_api_user
    - zabbix_api_pass
    - zabbix_url
  tags:
    - api

- name: "Including userparameters"
  include: "userparameter.yml"
  when: zabbix_agent_userparameters|length > 0
  tags:
    - zabbix-agent
    - userparameter
